"""forth

Revision ID: b8b4febe38ab
Revises: b91696dfba50
Create Date: 2023-02-22 11:01:00.222995

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'b8b4febe38ab'
down_revision = 'b91696dfba50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'updated_at')
    # ### end Alembic commands ###
